import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navbar } from '../Components/Navigations/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function UsersLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div lang="en">
            <div className={`${inter.className}`}>
                <div className='h-auto bg-[#DCDCDC] xl:px-48 lg:pt-10'>
                    <div className='bg-white'>
                    <div className="z-20 w-full h-auto">
                        <Navbar />
                    </div>
                    <div className='p-3'>
                        {children}
                    </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
